### ISSUE TITLE
Repo seems to be down

### ISSUE THREAD

**Issue by AronL** [Babyyoda777/babyyoda777.github.io#4]
Hey BabyYoda,

I am not able to access your jailbreak repo. (Getting a 404) 

Figured I should let you know.

Thanks!

**Comment by Babyyoda777** [comment]
Oh sorry! You can use https://babyyoda777.github.io or you can use https://babyyoda777.tech both are the exact same repo with same stuff. Sorry I had a domain change. For the future incase I change it again, use https://babyyoda777.github.io

**Comment by AronL** [comment]
Sweet, thank you!

Aron

I typed this with my thumbs. Please excuse my brevity.

**Comment by AronL** [comment]
It looks like the repo might be down again :(



I typed this with my thumbs. Please excuse my brevity.

**Comment by Babyyoda777** [comment]
Back up now

**Comment by AronL** [comment]
Sadly still seems to be down :(



I typed this with my thumbs. Please excuse my brevity.
